apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.registryService.name }}-deployment 
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.registryService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.registryService.name }}
    spec:
      containers:
      - name: proof-program-registry-service
        image: {{ .Values.registryService.image }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: ipfs-storage
          mountPath: /data
        env:
        - name: DATABASE_PATH
          value: /data/db.sqlite
      volumes:
      - name: ipfs-storage
        persistentVolumeClaim:
          claimName: {{ .Values.registryService.name }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.registryService.name }}-pvc 
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.registryService.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.registryService.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30808  
