services:
  proof-program-registry:
    container_name: proof-program-registry
    build:
      context: .
    ports:
      - "6005:8080"  # Exposes your app on port 6005
    depends_on:
      - ipfs-service    # Ensures IPFS starts first
    tty: true
    stdin_open: true

  ipfs-service:
    container_name: ipfs-service
    image: ipfs/kubo:v0.35.0
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080:8080"   # Gateway
      - "5001:5001"   # API
    volumes:
      - ./ipfs_data:/data/ipfs
    restart: unless-stopped
    tty: true
    stdin_open: true
